import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { SignIn, useUser, SignInButton, SignOutButton } from "@clerk/nextjs";

export default function Home() {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center">
        <div className="w-full max-w-2xl bg-red-200">
          <div>
            {!user.isSignedIn && <SignInButton />}
            {!!user.isSignedIn && <SignOutButton />}
          </div>
          <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          <div>
            {data?.map((post) => (
              <div key={post.id}>{post.content}</div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
