import Head from "next/head";
import { type NextPage } from "next";
import { useUser } from "@clerk/nextjs";

export default function SinglePostPage() {
  return (
    <>
      <Head>
        <title>Post</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="flex h-screen justify-center">
        <div>Post View</div>
      </main>
    </>
  );
}
